// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let supabaseClient: any = null;

async function createSupabaseClient() {
  if (supabaseClient) {
    return supabaseClient;
  }

  try {
    // Try to create real Supabase client
    if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && SUPABASE_URL.includes('supabase.co')) {
      supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: false, // Disable auto refresh to prevent lock issues
        }
      });
      return supabaseClient;
    } else {
      throw new Error('Invalid Supabase configuration');
    }
  } catch (error) {
    console.warn('Supabase not available, using mock client for testing:', error.message);
    // Import and use mock client
    try {
      const { supabase: mockSupabase } = await import('./mock-client');
      supabaseClient = mockSupabase;
      return supabaseClient;
    } catch (mockError) {
      console.error('Failed to load mock client:', mockError);
      // Return a minimal fallback client
      supabaseClient = {
        auth: {
          signInWithPassword: async () => ({ data: null, error: { message: 'Client not available' } }),
          signOut: async () => ({ error: null }),
          getSession: async () => ({ data: { session: null } })
        },
        from: () => ({
          select: () => ({
            eq: () => ({
              eq: () => Promise.resolve({ data: [], error: null })
            }),
            order: () => ({
              then: (callback: any) => callback({ data: [], error: null })
            })
          }),
          update: () => ({
            eq: () => Promise.resolve({ error: null })
          })
        })
      };
      return supabaseClient;
    }
  }
}

// Export a proxy that lazily initializes the client
export const supabase = new Proxy({} as any, {
  get(target, prop) {
    if (!supabaseClient) {
      // Initialize synchronously for basic operations, async for others
      if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && SUPABASE_URL.includes('supabase.co')) {
        supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
          auth: {
            storage: localStorage,
            persistSession: true,
            autoRefreshToken: false,
          }
        });
      } else {
        // Return minimal client for build time
        return () => ({ data: [], error: null });
      }
    }
    return supabaseClient[prop];
  }
});