// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create supabase client with fallback to mock when unreachable
export const supabase = await (async () => {
  try {
    // Try to create real Supabase client
    if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && SUPABASE_URL.includes('supabase.co')) {
      // Test if Supabase is reachable
      const testResponse = await fetch(`${SUPABASE_URL}/rest/v1/`, {
        method: 'HEAD',
        mode: 'no-cors'
      }).catch(() => null);
      
      if (!testResponse) {
        throw new Error('Supabase URL not accessible');
      }
      
      return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: false, // Disable auto refresh to prevent lock issues
        }
      });
    } else {
      throw new Error('Invalid Supabase configuration');
    }
  } catch (error) {
    console.warn('Supabase not available, using mock client for testing:', error.message);
    // Import and use mock client
    try {
      const { supabase: mockSupabase } = await import('./mock-client');
      return mockSupabase;
    } catch (mockError) {
      console.error('Failed to load mock client:', mockError);
      // Return a minimal fallback client
      return {
        auth: {
          signInWithPassword: async () => ({ data: null, error: { message: 'Client not available' } }),
          signOut: async () => ({ error: null }),
          getSession: async () => ({ data: { session: null } })
        },
        from: () => ({
          select: () => ({
            eq: () => ({
              eq: () => Promise.resolve({ data: [], error: null })
            }),
            order: () => ({
              then: (callback: any) => callback({ data: [], error: null })
            })
          }),
          update: () => ({
            eq: () => Promise.resolve({ error: null })
          })
        })
      };
    }
  }
})();